name: xclim-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - nc-time-axis=1.2
  - matplotlib
  - cartopy[version='>=0.19']
  - notebook
  - xclim==0.27
  - birdy
  - xarray==0.19
  - pandas==1.3.3
  - cftime==1.4.1
