#!/bin/bash
set -ex

# ## We create a second environment for finch, from the latest release.

# # Get finch's env file
curl -o env_finch.yml https://raw.githubusercontent.com/bird-house/finch/f2943c754a9ee21af4ffa5d8db98a7a7f2e4c2d7/environment.yml

# # Create finch's env
conda env create -f env_finch.yml -n finch-demo

# # Install finch in its env
conda run -n finch-demo python -m pip install finch==0.7.5
